### ISSUE TITLE
Sharing reformatter configurations

### ISSUE THREAD

**Issue by DamienCassou** [purcell/emacs-reformatter#56] opened 2024-09-01 08:35 UTC
Some reformatters are easier to configure than others. Is there a place where we could share reformatter's configurations?

Some ideas:

1. Each configuration goes into a dedicated repository/project, maintained by her/his creator and declared on ELPA:  this is a lot of effort to share a few lines.
2. A dedicated "reformatters" repository/project (similar to [yasnippet snippets](https://github.com/AndreaCrotti/yasnippet-snippets)): this requires advertising the repository from "emacs-reformatter" and a couple of maintainers.
3. Dedicated files in "emacs-reformatter" repository: this means you become responsible for reviewing and merging all PRs until you let other maintainers in. Probably the easiest solution for users.
4. A wiki in "emacs-reformatter" repository: easy to setup and doesn't require much maintenance but requires navigating, reading and copy/pasting from your users.

**Comment by purcell** [comment] 2024-09-03 09:54
I've been doing (1) quite a lot, and I've also changed a couple of major modes I co-maintain (e.g. `elm-mode`) to use `reformatter` internally. My goal with this project was to extract the boilerplate for running reformatters, since I saw it was differently (and sometimes poorly) implemented elsewhere. However, I don't particularly want to get into maintaining a big set of reformatter configurations, so (2) and (3) aren't very appealing to me: for that, there is `format-all` and `apheleia`. I'd be happy to publish some examples alongside this project I guess — that might just be a case of expanding `reformatter-tests.el` and suggesting people take a look at it.

**Comment by DamienCassou** [comment] 2024-09-03 14:11
From what I understand, you see `reformatter` more as a library than an end-user tool. Which explains why you don't want to care much about sharing user configs. It all makes sense to me.

I'm not sure I would want to expand `reformatter-tests.el` to include examples because:
- running tests will then require external dependencies;
- to be reproducible and testable, examples will probably not really look like what users would need to add to their `init.el`

We could create an integration test suite instead but it seems like a lot of work and knowledge about many tools.

Feel free to close the issue.

**Comment by purcell** [comment] 2024-09-04 09:23
> From what I understand, you see `reformatter` more as a library than an end-user tool. Which explains why you don't want to care much about sharing user configs. It all makes sense to me.

Yeah, pretty much.

> We could create an integration test suite instead but it seems like a lot of work and knowledge about many tools.

I should probably do this anyway for a few tools, just for regression purposes, but that's beyond the scope of this ticket so I'll go ahead and close this. Thanks!

**Closed by purcell** 2024-09-04 09:23 UTC
